// Generates docs/lib/canvg.global.js, a CLASSIC-SCRIPT build of canvg, from
// docs/lib/canvg.js, the self-contained ES module build.
//
// canvg 4.x publishes ES modules only, so a page had to bridge it with a
// <script type="module"> of its own before the viewer could offer PNG export
// and Copy PNG. A site that concatenates its scripts into one classic bundle
// -- BV-BRC does, and its 3.x page offered neither (2026-10-08) -- cannot put
// a module in it. This build can be a plain <script src> or one more file in
// such a bundle: the module's body wrapped in a strict-mode function (module
// code is always strict; the wrapper keeps it so), its one export statement
// replaced by `window.Canvg = <the module's Canvg>`, the licence comment kept,
// the source-map pointer dropped (there is no map for this file).
//
//   node test/make_canvg_global.js            writes docs/lib/canvg.global.js
//   node test/make_canvg_global.js --check    exits 1 if the file on disk differs
//
// test/canvg_global_test.js compares the file on disk with build() in
// process, so the generated file can never drift from its source;
// test/browser/exports.html loads the build from a plain script tag and saves
// and copies a PNG through it; test/browser/canvg_global.html checks what is
// offered with and without it.

'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.join(__dirname, '..', 'docs', 'lib', 'canvg.js');
const OUT = path.join(__dirname, '..', 'docs', 'lib', 'canvg.global.js');

function build() {
    const src = fs.readFileSync(SRC, 'utf8');
    // the version, from the source file's own header: the one place it is stated
    const version = (src.slice(0, 2000).match(/canvg (\d+\.\d+\.\d+)/) || [])[1];
    if (!version) {
        throw new Error('no "canvg <version>" in the header of ' + SRC);
    }
    // the module's one export statement
    const exportsAt = src.lastIndexOf('export{');
    if (exportsAt < 0 || src.indexOf('export{') !== exportsAt) {
        throw new Error('expected exactly one export statement in ' + SRC);
    }
    const tail = src.slice(exportsAt);
    const stmt = tail.match(/^export\{[^}]*\};?/);
    if (!stmt) {
        throw new Error('cannot read the export statement of ' + SRC);
    }
    // after it: only the licence comment and the source-map pointer
    const after = tail.slice(stmt[0].length);
    if (!/^\s*(\/\*[\s\S]*?\*\/\s*)*(\/\/# sourceMappingURL=\S*\s*)?$/.test(after)) {
        throw new Error('code follows the export statement in ' + SRC);
    }
    const m = stmt[0].match(/(?:^export\{|,)\s*([A-Za-z_$][\w$]*) as Canvg\s*(?:,|\})/);
    if (!m) {
        throw new Error('no "<name> as Canvg" in the export statement of ' + SRC);
    }
    const body = src.slice(0, exportsAt) + after.replace(/\/\/# sourceMappingURL=\S*\s*$/, '');
    const text = '/*\n'
        + ' * canvg ' + version + ' -- classic-script build, GENERATED by test/make_canvg_global.js\n'
        + ' * from docs/lib/canvg.js (the self-contained ES module build; see its header).\n'
        + ' * Do not edit: regenerate.\n'
        + ' *\n'
        + ' * The module\'s body in a strict-mode function, its export statement replaced\n'
        + ' * by one assignment, so a plain <script src="canvg.global.js"> -- or this\n'
        + ' * file concatenated into a site\'s bundle -- defines window.Canvg, which is\n'
        + ' * what Archaeopteryx.js looks for to offer PNG export and Copy PNG.\n'
        + ' * Licence: canvg\'s (MIT).\n'
        + ' */\n'
        + '(function () {\n'
        + '\'use strict\';\n'
        + body.replace(/\s+$/, '') + '\n'
        + 'window.Canvg = ' + m[1] + ';\n'
        + '})();\n';
    // The real test of "wraps as a classic script": it must PARSE as one. A
    // leftover import, a top-level await, import.meta -- anything a module
    // may hold and a classic script may not -- fails here, by name, instead
    // of in every browser that loads the file.
    try {
        new vm.Script(text, {filename: 'canvg.global.js'});
    } catch (e) {
        throw new Error('the wrapped module does not parse as a classic script: ' + e.message);
    }
    return text;
}

module.exports = {build: build, SRC: SRC, OUT: OUT};

if (require.main === module) {
    const text = build();
    if (process.argv.includes('--check')) {
        const onDisk = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
        if (onDisk !== text) {
            console.error(path.relative(process.cwd(), OUT) + ' differs from a fresh generation; run node test/make_canvg_global.js');
            process.exit(1);
        }
        console.log('docs/lib/canvg.global.js is up to date');
    } else {
        fs.writeFileSync(OUT, text);
        console.log('wrote ' + path.relative(process.cwd(), OUT) + ' (' + text.length + ' bytes, Canvg = '
            + text.match(/window\.Canvg = (\w+);/)[1] + ')');
    }
}
