// Generates docs/lib/canvg.global.js, a CLASSIC-SCRIPT build of canvg, from
// docs/lib/canvg.js, the self-contained ES module build.
//
// canvg 4.x publishes ES modules only, so a page had to bridge it with a
// <script type="module"> of its own before the viewer could offer PNG export
// and Copy PNG. A site that concatenates its scripts into one classic bundle
// -- BV-BRC does, and its 3.x page offered neither (2026-10-08) -- cannot put
// a module in it. This build can be a plain <script src> or one more file in
// such a bundle: the module's body wrapped in a function, its one export
// statement replaced by `window.Canvg = <the module's Canvg>`.
//
//   node test/make_canvg_global.js            writes docs/lib/canvg.global.js
//   node test/make_canvg_global.js --check    exits 1 if the file on disk differs
//
// test/canvg_global_test.js runs the check, so the generated file can never
// drift from its source; test/browser/canvg_global.html proves the build
// exports a PNG from a plain script tag.

'use strict';

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'docs', 'lib', 'canvg.js');
const OUT = path.join(__dirname, '..', 'docs', 'lib', 'canvg.global.js');

function build() {
    const src = fs.readFileSync(SRC, 'utf8');
    // the module's one export statement, at its very end
    const exportsAt = src.lastIndexOf('export{');
    if (exportsAt < 0 || src.indexOf('export{') !== exportsAt) {
        throw new Error('expected exactly one export statement in ' + SRC);
    }
    const tail = src.slice(exportsAt);
    // after it: only the licence comment and the source-map pointer
    const stmt = tail.match(/^export\{[^}]*\};?/);
    if (!stmt) {
        throw new Error('cannot read the export statement of ' + SRC);
    }
    const after = tail.slice(stmt[0].length);
    if (!/^\s*(\/\*[\s\S]*?\*\/\s*)*(\/\/# sourceMappingURL=\S*\s*)?$/.test(after)) {
        throw new Error('code follows the export statement in ' + SRC);
    }
    const m = stmt[0].match(/(?:^export\{|,)\s*([A-Za-z_$][\w$]*) as Canvg\s*(?:,|\})/);
    if (!m) {
        throw new Error('no "<name> as Canvg" in the export statement of ' + SRC);
    }
    for (const bad of ['import.meta', 'import(', '\nawait ']) {
        if (src.indexOf(bad) >= 0) {
            throw new Error('the module build uses ' + JSON.stringify(bad) + ', which a classic script cannot');
        }
    }
    // the licence comment stays; the map pointer goes (there is no map for this file)
    const body = src.slice(0, exportsAt) + after.replace(/\/\/# sourceMappingURL=\S*\s*$/, '');
    return '/*\n'
        + ' * canvg 4.0.3 -- classic-script build, GENERATED by test/make_canvg_global.js\n'
        + ' * from docs/lib/canvg.js (the self-contained ES module build; see its header).\n'
        + ' * Do not edit: regenerate.\n'
        + ' *\n'
        + ' * The module\'s body in a function, its export statement replaced by one\n'
        + ' * assignment, so a plain <script src="canvg.global.js"> -- or this file\n'
        + ' * concatenated into a site\'s bundle -- defines window.Canvg, which is\n'
        + ' * what Archaeopteryx.js looks for to offer PNG export and Copy PNG.\n'
        + ' * Licence: canvg\'s (MIT).\n'
        + ' */\n'
        + '(function () {\n'
        + body.replace(/\s+$/, '') + '\n'
        + 'window.Canvg = ' + m[1] + ';\n'
        + '})();\n';
}

const text = build();
if (process.argv.includes('--check')) {
    const onDisk = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
    if (onDisk !== text) {
        console.error(path.relative(process.cwd(), OUT) + ' differs from a fresh generation; run node test/make_canvg_global.js');
        process.exit(1);
    }
    console.log('docs/lib/canvg.global.js is up to date');
} else {
    fs.writeFileSync(OUT, text);
    console.log('wrote ' + path.relative(process.cwd(), OUT) + ' (' + text.length + ' bytes, Canvg = ' + text.match(/window\.Canvg = (\w+);/)[1] + ')');
}
